name: CI/CD for Parking System

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master


jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t preethika1801/parking-system:latest .

    - name: Push Docker image
      run: docker push preethika1801/parking-system:latest
